// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNVRXVqWHTFgMJKqpil61D9Vs756dxxYc',
    appId: '1:160315855672:web:7b0ffe02ad77d8fb6e27cd',
    messagingSenderId: '160315855672',
    projectId: 'pragj-bad7a',
    authDomain: 'pragj-bad7a.firebaseapp.com',
    storageBucket: 'pragj-bad7a.appspot.com',
    measurementId: 'G-C4VES481N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCK1ioHJLAiMSKIuFPc7d1ESoPRfAFGTc',
    appId: '1:160315855672:android:f898ad79dad850386e27cd',
    messagingSenderId: '160315855672',
    projectId: 'pragj-bad7a',
    storageBucket: 'pragj-bad7a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfppN4uq4ZtB1NX8Ij2QCVzTct4S_wtUE',
    appId: '1:160315855672:ios:29bee2d191a745c06e27cd',
    messagingSenderId: '160315855672',
    projectId: 'pragj-bad7a',
    storageBucket: 'pragj-bad7a.appspot.com',
    iosClientId: '160315855672-53hmacnugkfqmg4a7u0gu75kj03vl8pu.apps.googleusercontent.com',
    iosBundleId: 'com.example.pragj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfppN4uq4ZtB1NX8Ij2QCVzTct4S_wtUE',
    appId: '1:160315855672:ios:8cea447e2569ed7b6e27cd',
    messagingSenderId: '160315855672',
    projectId: 'pragj-bad7a',
    storageBucket: 'pragj-bad7a.appspot.com',
    iosClientId: '160315855672-ug8fl3jb673el53hqd54aqtregisbuc3.apps.googleusercontent.com',
    iosBundleId: 'com.example.pragj.RunnerTests',
  );
}
